# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
logo: "/assets/images/vc1-1.png"
locale: "fr-FR"
title: PROMOTEUR
email: oleksandr.vidomenko.it@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Chacun peut assurer la sécurité des informations de son domicile ou de son entreprise, de manière autonome et pour peu d’argent. Avec l'aide de mon développement, il s'agit d'un cluster tolérant aux pannes dans une implémentation ultra-bon marché. Il s'agit d'un système open source, un cluster à deux nœuds basé sur PROXMOX, dont le logiciel exécute certaines tâches.
twitter_username: username
github_username: vidomenko-it
minimal_mistakes_skin: air
search: true
# _config.yml (defaults)
repository: "vidomenko-it/vidomenko-it.github.io"  # e.g. "mmistakes/minimal-mistakes"
comments:
#  provider: "staticman_v2"
#  staticman:
#    branch: "main"
#    endpoint: "https://{vidomenko comment v3 API}/v3/entry/github/"
reCaptcha:
#  enabled: true
#  siteKey: "6LdSs9gqAAAAAI9DXmw6Gtx28mEFdA1YR9EdGyx7"
#  secret: "6LdSs9gqAAAAABKMK1EL3YkkRERCCLE-vaTnOnjQ"


# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
enable_copy_code_button: true

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "GTM-K97D8HL8"
    anonymize_ip: false # default

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Oleksandr Vidomenko"
  avatar : "/assets/images/Sasha1.jpg"
  bio    : "Je travaille dans le domaine informatique depuis plus de 20 ans."
  location: "Thionville, France"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://e-schop.biz.ua/kickstart/"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/oleksandr-vidomenko-191295317/"
   #- label: "Twitter"
   #  icon: "fab fa-fw fa-twitter-square"
   #  url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/vidomenko-it/"
    - label: "Email"
      icon: "fa-solid fa-envelope"
      url: "mailto:oleksandr.vidomenko.it@gmail.com"
   #- label: "Instagram"
   #  icon: "fab fa-fw fa-instagram"
   #  url: "https://instagram.com/"
             

footer:
  links:
   #- label: "Twitter"
   #  icon: "fab fa-fw fa-twitter-square"
   #  url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/vidomenko-it/"
   #- label: "Instagram"
   #  icon: "fab fa-fw fa-instagram"
   #  url: "https://instagram.com/"
    - label: "Email"
      icon: "fa-solid fa-envelope"
      url: "mailto:oleksandr.vidomenko.it@gmail.com"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      enable_copy_code_button: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
  enable_copy_code_button: true
